### ISSUE TITLE
Transaction underpriced

### ISSUE THREAD

**Issue by visopsys** [ava-labs/avalanche-smart-contract-quickstart#12]
I have successfully assigned some values for each of accounts but failed to send avax to them or deploy a contract. 

Running
```
yarn balances --network avash
```
results
```
0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC has balance 1000000000000000000000
0x9632a79656af553F58738B0FB750320158495942 has balance 1000000000000000000000
0x55ee05dF718f1a5C1441e76190EB1a19eE2C9430 has balance 1000000000000000000000
0x4Cf2eD3665F6bFA95cE6A11CFDb7A2EF5FC1C7E4 has balance 1000000000000000000000
0x0B891dB1901D4875056896f28B6665083935C7A8 has balance 1000000000000000000000
0x01F253bE2EBF0bd64649FA468bF7b95ca933BDe2 has balance 1000000000000000000000
0x78A23300E04FB5d5D2820E23cc679738982e1fd5 has balance 1000000000000000000000
0x3C7daE394BBf8e9EE1359ad14C1C47003bD06293 has balance 1000000000000000000000
0x61e0B3CD93F36847Abbd5d40d6F00a8eC6f3cfFB has balance 1000000000000000000000
0x0Fa8EA536Be85F32724D57A37758761B86416123 has balance 1000000000000000000000
```

but running
```
 yarn send-avax --network avash
```

results

```
Seeding addresses with AVAX
ProviderError: transaction underpriced
```

Anyone knows why?

**Comment by erikoganesian** [comment]
I have the exact same issue. Some help would be great.

**Comment by cgcardona** [comment]
The fee level is set in the local genesis within avalanchego. I believe they you need to make sure that they're running the latest avalanchego code and the local genesis should contain the update.

Can you confirm you're running AvalancheGo v1.3.1? https://github.com/ava-labs/avalanchego/releases/tag/v1.3.1

**Comment by erikoganesian** [comment]
I am running 1.2.4. Will get back to you if it still doesn't work after the upgrade.

**Comment by cgcardona** [comment]
FYI v1.3.2 is live now https://github.com/ava-labs/avalanchego/releases/tag/v1.3.2

**Comment by cgcardona** [comment]
Did this work?

**Comment by visopsys** [comment]
Replied in this [thread](https://github.com/ava-labs/avalanche-smart-contract-quickstart/issues/11#issuecomment-821288233).

**Comment by visopsys** [comment]
Closing this one.
